/**
 * Icon catalog data for the Foundations/Icons story.
 * Every Lucide icon actively used in the app, grouped by category.
 *
 * @see components/foundations/Icons.stories.tsx for the rendered catalog
 */
import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertCircle,
  AlignCenter,
  AlignLeft,
  AlignRight,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowDownIcon,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart3,
  Bell,
  Bold,
  BookIcon,
  BrainIcon,
  Briefcase,
  Building2,
  Calendar,
  CalendarClock,
  CalendarDays,
  Check,
  CheckCircle,
  CheckIcon,
  CheckSquare,
  ChevronDown,
  ChevronDownIcon,
  ChevronLeft,
  ChevronLeftIcon,
  ChevronRight,
  ChevronRightIcon,
  ChevronUp,
  ChevronUpIcon,
  ChevronsUpDown,
  CircleIcon,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Copy,
  CopyIcon,
  Crown,
  Database,
  DollarSign,
  DownloadIcon,
  Eye,
  ExternalLink,
  FileCheck,
  FileSignature,
  FileText,
  Github,
  Globe,
  GripVertical,
  GripVerticalIcon,
  Italic,
  KeyRound,
  Layers,
  LayoutDashboard,
  Link2,
  Loader2,
  Loader2Icon,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  MinusIcon,
  Monitor,
  Moon,
  MoreHorizontal,
  PanelLeftIcon,
  Pause,
  Pencil,
  Phone,
  PieChart,
  Plus,
  Repeat,
  Search,
  SearchIcon,
  Send,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  Star,
  Sun,
  Terminal,
  Trash2,
  Underline,
  User,
  UserCog,
  UserPlus,
  Users,
  Variable,
  Video,
  Workflow,
  X,
  XCircle,
  XIcon,
} from "lucide-react";

/** A single icon entry with its display name. */
export interface IconEntry {
  name: string;
  icon: LucideIcon;
}

/** A category grouping icons by usage area. */
export interface IconCategory {
  label: string;
  description: string;
  icons: IconEntry[];
}

/** All icon categories used across the application. */
export const ICON_CATALOG: IconCategory[] = [
  {
    label: "Navigation & Layout",
    description: "App chrome, sidebar, menus, and page structure",
    icons: [
      { name: "LayoutDashboard", icon: LayoutDashboard },
      { name: "PanelLeftIcon", icon: PanelLeftIcon },
      { name: "Briefcase", icon: Briefcase },
      { name: "Building2", icon: Building2 },
      { name: "Settings", icon: Settings },
      { name: "Settings2", icon: Settings2 },
      { name: "Bell", icon: Bell },
      { name: "Globe", icon: Globe },
      { name: "LogOut", icon: LogOut },
      { name: "ArrowLeft", icon: ArrowLeft },
      { name: "ArrowRight", icon: ArrowRight },
      { name: "ExternalLink", icon: ExternalLink },
      { name: "MoreHorizontal", icon: MoreHorizontal },
    ],
  },
  {
    label: "Chevrons & Arrows",
    description: "Directional indicators for menus, accordions, pagination",
    icons: [
      { name: "ChevronDown", icon: ChevronDown },
      { name: "ChevronDownIcon", icon: ChevronDownIcon },
      { name: "ChevronUp", icon: ChevronUp },
      { name: "ChevronUpIcon", icon: ChevronUpIcon },
      { name: "ChevronLeft", icon: ChevronLeft },
      { name: "ChevronLeftIcon", icon: ChevronLeftIcon },
      { name: "ChevronRight", icon: ChevronRight },
      { name: "ChevronRightIcon", icon: ChevronRightIcon },
      { name: "ChevronsUpDown", icon: ChevronsUpDown },
      { name: "ArrowUp", icon: ArrowUp },
      { name: "ArrowDown", icon: ArrowDown },
      { name: "ArrowDownIcon", icon: ArrowDownIcon },
    ],
  },
  {
    label: "Actions",
    description: "CRUD operations and interactive controls",
    icons: [
      { name: "Plus", icon: Plus },
      { name: "X", icon: X },
      { name: "XIcon", icon: XIcon },
      { name: "Eye", icon: Eye },
      { name: "Pencil", icon: Pencil },
      { name: "Trash2", icon: Trash2 },
      { name: "Copy", icon: Copy },
      { name: "CopyIcon", icon: CopyIcon },
      { name: "Archive", icon: Archive },
      { name: "ArchiveRestore", icon: ArchiveRestore },
      { name: "Search", icon: Search },
      { name: "SearchIcon", icon: SearchIcon },
      { name: "Send", icon: Send },
      { name: "DownloadIcon", icon: DownloadIcon },
      { name: "GripVertical", icon: GripVertical },
      { name: "GripVerticalIcon", icon: GripVerticalIcon },
    ],
  },
  {
    label: "Status & Feedback",
    description: "Confirmations, warnings, loading states",
    icons: [
      { name: "Check", icon: Check },
      { name: "CheckIcon", icon: CheckIcon },
      { name: "CheckCircle", icon: CheckCircle },
      { name: "CheckSquare", icon: CheckSquare },
      { name: "XCircle", icon: XCircle },
      { name: "CircleIcon", icon: CircleIcon },
      { name: "AlertCircle", icon: AlertCircle },
      { name: "Loader2", icon: Loader2 },
      { name: "Loader2Icon", icon: Loader2Icon },
      { name: "Star", icon: Star },
      { name: "Terminal", icon: Terminal },
    ],
  },
  {
    label: "People & Permissions",
    description: "Users, teams, roles, and access control",
    icons: [
      { name: "User", icon: User },
      { name: "Users", icon: Users },
      { name: "UserPlus", icon: UserPlus },
      { name: "UserCog", icon: UserCog },
      { name: "Crown", icon: Crown },
      { name: "KeyRound", icon: KeyRound },
      { name: "Shield", icon: Shield },
      { name: "ShieldCheck", icon: ShieldCheck },
    ],
  },
  {
    label: "Hiring Pipeline",
    description: "Positions, candidates, applications, evaluations",
    icons: [
      { name: "ClipboardList", icon: ClipboardList },
      { name: "ClipboardCheck", icon: ClipboardCheck },
      { name: "Layers", icon: Layers },
      { name: "FileText", icon: FileText },
      { name: "FileCheck", icon: FileCheck },
      { name: "FileSignature", icon: FileSignature },
      { name: "Pause", icon: Pause },
      { name: "Activity", icon: Activity },
      { name: "Workflow", icon: Workflow },
    ],
  },
  {
    label: "Scheduling & Calendar",
    description: "Dates, times, interviews, availability",
    icons: [
      { name: "Calendar", icon: Calendar },
      { name: "CalendarClock", icon: CalendarClock },
      { name: "CalendarDays", icon: CalendarDays },
      { name: "Clock", icon: Clock },
      { name: "Repeat", icon: Repeat },
      { name: "Video", icon: Video },
      { name: "Phone", icon: Phone },
      { name: "Monitor", icon: Monitor },
      { name: "Link2", icon: Link2 },
    ],
  },
  {
    label: "Communication",
    description: "Messaging, email, notifications",
    icons: [
      { name: "Mail", icon: Mail },
      { name: "MessageCircle", icon: MessageCircle },
      { name: "MessageSquare", icon: MessageSquare },
      { name: "MapPin", icon: MapPin },
      { name: "DollarSign", icon: DollarSign },
      { name: "Variable", icon: Variable },
    ],
  },
  {
    label: "Data & Analytics",
    description: "Charts, databases, reporting",
    icons: [
      { name: "BarChart3", icon: BarChart3 },
      { name: "PieChart", icon: PieChart },
      { name: "Database", icon: Database },
    ],
  },
  {
    label: "Theme & Appearance",
    description: "Light/dark mode toggles",
    icons: [
      { name: "Sun", icon: Sun },
      { name: "Moon", icon: Moon },
    ],
  },
  {
    label: "AI & Chat",
    description: "AI assistant, reasoning, sources",
    icons: [
      { name: "BrainIcon", icon: BrainIcon },
      { name: "BookIcon", icon: BookIcon },
    ],
  },
  {
    label: "Text Formatting",
    description: "Rich text editor controls (story-only references)",
    icons: [
      { name: "Bold", icon: Bold },
      { name: "Italic", icon: Italic },
      { name: "Underline", icon: Underline },
      { name: "AlignLeft", icon: AlignLeft },
      { name: "AlignCenter", icon: AlignCenter },
      { name: "AlignRight", icon: AlignRight },
      { name: "MinusIcon", icon: MinusIcon },
    ],
  },
  {
    label: "Auth & Identity",
    description: "Authentication providers and methods",
    icons: [
      { name: "Github", icon: Github },
    ],
  },
];
